data model changes to add name, id and dependency for sr annotaiton
prbarl/zipkin-azure pull request #5
Opened 2017-06-26 23:32 UTC by praveenbarli

2017-06-26 23:35 UTC, SergeyKanzhelev commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +        telemetry.getContext().getOperation().setName(span.name);
`span.name` should got to `dependency.name` or `request.name`. Setting it on operation context is optional

2017-06-26 23:36 UTC, SergeyKanzhelev commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +            telemetry.trackDependency(Constants.SERVER_RECV, "request", new Duration(span.duration==null?0L:span.duration),
`SERVER_RECV` means server received? When server receives - you need to track `request`. Dependency is when client send outgoing request.

2017-06-26 23:37 UTC, SergeyKanzhelev commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +        String traceIdHigh = Long.toString(span.traceIdHigh);
is there parent ID? Can you please place it into custom property for now.

2017-06-26 23:37 UTC, SergeyKanzhelev requested changes
see comments

2017-06-27 17:29 UTC, SergeyKanzhelev commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +<<<<<<< HEAD
oh, something went wrong here

2017-06-27 17:36 UTC, praveenbarli commented
Hi @SergeyKanzhelev, Added request on SS annotation and parentid to customprops. Please review.

2017-06-27 19:03 UTC, SergeyKanzhelev commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +            String spanName = span.name !=null && !span.name.isEmpty()?span.name:Constants.CLIENT_SEND;
does span in Zipkin has special annotation for an error? In Application Insights we rely on `failure` flag for many scenarios. So if we can deduct that span failed from annotations - it will improve those scenarios.

2017-06-27 19:07 UTC, SergeyKanzhelev commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +        telemetry.getContext().getOperation().setId(traceId);
I think it should be a combination of two ids - `traceIdHigh` and `traceId`

2017-06-27 19:08 UTC, SergeyKanzhelev approved these changes
Looks OK. Please address comments

2017-06-27 19:18 UTC, praveenbarli commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +            String spanName = span.name !=null && !span.name.isEmpty()?span.name:Constants.CLIENT_SEND;
Yes, they suggest logging a  [binary annotation](https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/Constants.java#L150) and have an open [issue] (https://github.com/openzipkin/openzipkin.github.io/issues/52). We shall discuss further how we set AI flag.

2017-06-27 19:20 UTC, praveenbarli commented on storage/applicationinsights/src/main/java/zipkin/storage/applicationinsights/ApplicationInsightsSpanConsumer.java
> +        telemetry.getContext().getOperation().setId(traceId);
Yes, Shall I concatenate both strings while setting id? How are we going to retrieve back?

2017-06-29 00:07 UTC, merged